<?php

namespace api\controllers;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\helpers\Url;

class SiteController extends Controller
{
    public function  actionIndex(){
        return [
            'success' => "Booking Api!!"
        ];
    }
    public function actionError()
    {
        return [
            'error' => "Error!!!!"
        ];
//        if (($exception = Yii::$app->getErrorHandler()->exception) === null) {
//            $exception = new NotFoundHttpException('yii', 'Page not found.');
//        }
//
//        if ($exception instanceof \HttpException) {
//            Yii::$app->response->setStatusCode($exception->getCode());
//        } else {
//            Yii::$app->response->setStatusCode(500);
//        }
//
//        return $this->asJson(['error' => $exception->getMessage(), 'code' => $exception->getCode()]);
    }
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}